# Generated by Django 3.1.7 on 2021-03-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_feature_productfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندیها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'ویژگیهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'سفارش شده ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name_plural': 'ویژگیهای محصولات'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'آدرسهای حمل'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
