# Generated by Django 3.1.7 on 2021-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_quantity', models.BooleanField(default=True, verbose_name='نمایش کالاهای بدون موجودی')),
            ],
        ),
    ]
