# Generated by Django 3.1.7 on 2021-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210323_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name_plural': 'تنظیمات اصلی سایت'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
