# Generated by Django 3.1.7 on 2021-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210323_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='show_quantity',
            field=models.BooleanField(default=True, verbose_name='نمایش موجودی کالا'),
        ),
    ]
