# Generated by Django 3.1.7 on 2021-03-23 20:25

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210323_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, to='store.Category'),
        ),
    ]
