# Generated by Django 3.1.7 on 2021-03-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210324_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='MalekRayan', max_length=200),
            preserve_default=False,
        ),
    ]
